---
title: "USF Covid Cases"
author: "Kramer Lab"
date: "9/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
library(tidyverse)      # data manipulation and visualization
library(lubridate)      # easily work with dates and times
library(tibbletime)     # working with time series data
library(zoo) # working with time series data)
library(reshape2)
library(ggplot2)


covid_usf <- read.csv("https://raw.githubusercontent.com/amsmith8/usf-covid-cases/master/usf_covid_cases.csv",
                      stringsAsFactors = FALSE)
covid_usf$Date <- as_date(covid_usf$Date)

head( covid_usf )

tampa <- covid_usf[,c(1,3)]
tampa$Date <- as_date(tampa$Date)
```


```{r setup, include=FALSE}
cases_ma <- tampa %>%
  mutate(ma_7_days = rollmean(Tampa, k = 7, fill = NA),
         ma_15_days = rollmean(Tampa, k = 15, fill = NA),
         ma_30_days = rollmean(Tampa, k = 30, fill = NA),
         ma_60_days = rollmean(Tampa, k = 60, fill = NA))

cases_ma           # working with time series data)

```

```{r setup, include=FALSE}
a <- reshape2::melt(cases_ma,  id.var='Date')

ggplot(a, aes(x = Date, y = value, col = variable)) +
  geom_line()+
  ggtitle("USf Covid cases moving averages ")
```





